<?php if (isset($flash['success'])) : ?>
  <?php foreach ($flash['success'] as $mess): ?>
    <div> <p> <?= $mess ?> </p> </div>
  <?php endforeach ?>
<?php endif ?>

<?php if (count($users) !== 0) : ?>
<table>
  <?php foreach ($users as $user): ?>
    <tr>
      <td>
          <?= htmlspecialchars($user['nickname']) ?>
      </td>
    </tr>
  <?php endforeach ?>
</table>
<?php endif ?>

<div>
<p>Authorization</p>
<?php if (!isset($_SESSION['user'])) : ?>
<form action="/session" method="post">
  <div>
    <label>
      email
      <input type="text" name="user[email]" value="">
    </label>
  </div>
  <input type="submit" value="Sign In">
</form>

<?php else: ?>
<div>
  <?= htmlspecialchars($_SESSION['user']['email']) ?>
</div>
<div>
  <?= htmlspecialchars($_SESSION['user']['nickname']) ?>
</div>
<form action="/session" method="post">
  <input type="hidden" name="_METHOD" value="DELETE">
  <input type="submit" value="Sign Out">
</form>
<?php endif ?>
</div>